### PR TITLE
Added userfriendly text after too many login attempts 

### PR DESCRIPTION
**Pull request by aletaschner**
A simple solution to #35.

### CODE REVIEW

**Comment by aletaschner** [comment]
Happy Hacktoberfest!

**Comment by aletaschner** [comment]
Hello! Oh ok, I will be fixing this issues today, thanks for the reply!

**Comment by PVince81** [comment]
@karakayasemi second review ?

**Comment by aletaschner** [comment]
Hello! Sorry, I tried and could not correctly run the fixer then completely forgot to address this. I'll try to fix this today.

**Comment by karakayasemi** [comment]
Hey @aletaschner, please see my comment in here, translations are missing in your commit: https://github.com/owncloud/brute_force_protection/pull/36#pullrequestreview-161505642

Let me know If you need any help. Thanks.

**Comment by mmattel** [comment]
@karakayasemi I have made the changes as suggested, sorry for the three commits - phpcs-fixer :smile:

**Pull request closed without merging**
