### PR TITLE
FIX - Issues #35 - Better error message

### PR DESCRIPTION
**Pull request by bartko-s**

### CODE REVIEW

**Comment by bartko-s** [comment]
This sentence "Too many failed login attempts. Try again in %s hours." must be translated to all languages.

**Comment by karakayasemi** [comment]
Thanks for contributing. Php-cs-fixer is not happy. run composer install to install owncloud-code-style config. After that run below command to see styling errros :
````
vendor/bin/php-cs-fixer fix -v --diff --diff-format udiff --dry-run --allow-risky yes
````
To fix that errors:
````
vendor/bin/php-cs-fixer fix -v --diff --diff-format udiff --allow-risky yes
````

**Comment by bartko-s** [comment]
@karakayasemi
I change my code. Now remaining time is shown instead of how long user was banned. I don't know how to add unit tests. Current unit test don't check if error message(LoginException) was thrown.

**Comment by bartko-s** [comment]
@karakayasemi 
Its your turn. You can take care of the rest.

**Comment by karakayasemi** [comment]
I need to squash commits etc. Probably, I have not permission for force commit in your fork. I will close this PR and create another. Thanks.

**Pull request closed without merging**
