### PR TITLE
Bump max-version to 11.0.0.0

### PR DESCRIPTION
**Pull request by phil-davis**

### CODE REVIEW

**Comment by phil-davis** [comment]
This gets some stupid problem in Travis on the Oracle jobs!!!

**Comment by karakayasemi** [comment]
@phil-davis I met and resolved the oracle problem in this PR: But no one reviewed. Please review and if it is okay merge it: https://github.com/owncloud/brute_force_protection/pull/40

**Comment by phil-davis** [comment]
@karakayasemi thanks - I approved and merged your PR.
Rebased this one, and hopefully CI will pass.

**Comment by karakayasemi** [comment]
Thank for the quick review :). I believe it will pass this time.

**Pull request merged**
