### PR TITLE
Refine the app's description

### PR DESCRIPTION
**Pull request by settermjd**
While researching the app so that I can document it, https://github.com/owncloud/documentation/issues/4334, I started going through the description. However, while pretty clear, I felt that the wording could be further refined and tightened, so that it's sharper and easier to understand. 

:information_desk_person: No negative reflection is intended toward the original authors, by me saying this.

### CODE REVIEW

**Comment by settermjd** [comment]
Thanks for spotting my mistakes, @phil-davis. Both have been addressed.

**Comment by settermjd** [comment]
Thanks, @phil-davis. @pmaier1, can you review and let me know if you're ok with the proposed changes?

**Comment by DeepDiver1975** [comment]
commits are to be squashed ..

**Comment by mmattel** [comment]
Cool ! 👍

**Pull request merged**
